<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'If you forget the password you can' => 'Если вы забыли пароль вы можете',
    'restore it' => 'восстановить его',
    'Code name' => 'Кодовое название',
    'Create' => 'Создать',
    'Create role' => 'Добавить роль',
    'Create user' => 'Добавить пользователя',
    'Data' => 'Дата',
    'Description' => 'Описание',
    'E-mail' => 'E-mail',
    'Fill in the form below to register' => 'Заполните форму ниже для того, чтобы зарегистрироваться',
    'Incorrect username or password.' => 'Неверный email или пароль',
    'Log in' => 'Вход',
    'Login' => 'Вход',
    'Name' => 'Имя',
    'Password' => 'Пароль',
    'Permissions' => 'Права',
    'Please enter login and password:' => 'Пожалуйста введите логин и пароль',
    'Please enter new password' => 'Пожалуйста введите пароль',
    'Please enter your email address. On it we will send a letter with information on password recovery.' => 'Пожалуйста введите ваш email. На него мы отправим письмо с информацией по восстановлению пароля.',
    'Remember me' => 'Запомнить меня',
    'Request password reset' => 'Запрос сброса пароля',
    'Roles' => 'Роли',
    'Rule name' => 'Правило',
    'Save' => 'Сохранить',
    'Send' => 'Отправить',
    'Sign up' => 'Регистрация',
    'Status' => 'Статус',
    'This email address has already been taken.' => 'Этот e-mail уже используется другим пользователем',
    'Type' => 'Тип',
    'Update' => 'Редактировать',
    'Update role: {name}' => 'Редактирование роли: {name}',
    'Update user: {name}' => 'Редактирование пользователя: {name}',
    'User successfully created' => 'Пользователь успешно добавлен',
    'User successfully deleted' => 'Пользователь успешно удален',
    'User successfully updated' => 'Пользователь успешно обновлен',
    'Users' => 'Пользователи',
    'Users list' => 'Список',
];
