<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Code name' => '',
    'Create' => '',
    'Create role' => '',
    'Create user' => '',
    'Data' => '',
    'Deleted' => '',
    'Description' => '',
    'E-mail' => '',
    'Fill in the form below to register' => '',
    'If you forget the password you can' => '',
    'Incorrect username or password.' => '',
    'Log in' => '',
    'Login' => '',
    'Name' => '',
    'Password' => '',
    'Permissions' => '',
    'Please enter login and password:' => '',
    'Please enter new password' => '',
    'Please enter your email address. On it we will send a letter with information on password recovery.' => '',
    'Remember me' => '',
    'Request password reset' => '',
    'Roles' => '',
    'Rule name' => '',
    'Save' => '',
    'Send' => '',
    'Sign up' => '',
    'Status' => '',
    'This email address has already been taken.' => '',
    'Type' => '',
    'Update' => '',
    'Update role: {name}' => '',
    'Update user: {name}' => '',
    'User successfully created' => '',
    'User successfully deleted' => '',
    'User successfully updated' => '',
    'Users' => '',
    'Users list' => '',
    'restore it' => '',
];
